"""pricing table

Revision ID: d1d6c58173a9
Revises: 
Create Date: 2026-01-23 18:00:01.085320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1d6c58173a9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('peak_hours',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('city_code', sa.String(length=10), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.String(length=5), nullable=False),
    sa.Column('end_time', sa.String(length=5), nullable=False),
    sa.Column('multiplier', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_peak_hours_city_code'), 'peak_hours', ['city_code'], unique=False)
    op.create_table('pricing_calculations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('city_code', sa.String(length=10), nullable=True),
    sa.Column('pickup_lat', sa.Float(), nullable=True),
    sa.Column('pickup_lon', sa.Float(), nullable=True),
    sa.Column('dropoff_lat', sa.Float(), nullable=True),
    sa.Column('dropoff_lon', sa.Float(), nullable=True),
    sa.Column('vehicle_type', sa.Enum('bike', 'car', 'auto', 'premium_car', name='vehicletype'), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('duration_minutes', sa.Float(), nullable=False),
    sa.Column('base_fare', sa.Float(), nullable=False),
    sa.Column('distance_cost', sa.Float(), nullable=False),
    sa.Column('time_cost', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('peak_multiplier', sa.Float(), nullable=False),
    sa.Column('surge_multiplier', sa.Float(), nullable=False),
    sa.Column('final_fare', sa.Float(), nullable=False),
    sa.Column('minimum_fare_applied', sa.Boolean(), nullable=False),
    sa.Column('regulatory_cap_applied', sa.Boolean(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricing_calculations_city_code'), 'pricing_calculations', ['city_code'], unique=False)
    op.create_index(op.f('ix_pricing_calculations_request_id'), 'pricing_calculations', ['request_id'], unique=False)
    op.create_index(op.f('ix_pricing_calculations_user_id'), 'pricing_calculations', ['user_id'], unique=False)
    op.create_table('pricing_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('city_code', sa.String(length=10), nullable=False),
    sa.Column('state_code', sa.String(length=10), nullable=True),
    sa.Column('vehicle_type', sa.Enum('bike', 'car', 'auto', 'premium_car', name='vehicletype'), nullable=False),
    sa.Column('base_fare', sa.Float(), nullable=False),
    sa.Column('per_km_rate', sa.Float(), nullable=False),
    sa.Column('per_minute_rate', sa.Float(), nullable=False),
    sa.Column('minimum_fare', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricing_profiles_city_code'), 'pricing_profiles', ['city_code'], unique=False)
    op.create_index(op.f('ix_pricing_profiles_state_code'), 'pricing_profiles', ['state_code'], unique=False)
    op.create_index(op.f('ix_pricing_profiles_vehicle_type'), 'pricing_profiles', ['vehicle_type'], unique=False)
    op.create_table('regulatory_caps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('city_code', sa.String(length=10), nullable=True),
    sa.Column('state_code', sa.String(length=10), nullable=True),
    sa.Column('vehicle_type', sa.Enum('bike', 'car', 'auto', 'premium_car', name='vehicletype'), nullable=True),
    sa.Column('max_fare_amount', sa.Float(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regulatory_caps_city_code'), 'regulatory_caps', ['city_code'], unique=False)
    op.create_index(op.f('ix_regulatory_caps_state_code'), 'regulatory_caps', ['state_code'], unique=False)
    op.create_table('surge_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vehicle_type', sa.Enum('bike', 'car', 'auto', 'premium_car', name='vehicletype'), nullable=False),
    sa.Column('base_demand_threshold', sa.Float(), nullable=False),
    sa.Column('max_surge_multiplier', sa.Float(), nullable=False),
    sa.Column('surge_increment', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_surge_configs_vehicle_type'), 'surge_configs', ['vehicle_type'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_surge_configs_vehicle_type'), table_name='surge_configs')
    op.drop_table('surge_configs')
    op.drop_index(op.f('ix_regulatory_caps_state_code'), table_name='regulatory_caps')
    op.drop_index(op.f('ix_regulatory_caps_city_code'), table_name='regulatory_caps')
    op.drop_table('regulatory_caps')
    op.drop_index(op.f('ix_pricing_profiles_vehicle_type'), table_name='pricing_profiles')
    op.drop_index(op.f('ix_pricing_profiles_state_code'), table_name='pricing_profiles')
    op.drop_index(op.f('ix_pricing_profiles_city_code'), table_name='pricing_profiles')
    op.drop_table('pricing_profiles')
    op.drop_index(op.f('ix_pricing_calculations_user_id'), table_name='pricing_calculations')
    op.drop_index(op.f('ix_pricing_calculations_request_id'), table_name='pricing_calculations')
    op.drop_index(op.f('ix_pricing_calculations_city_code'), table_name='pricing_calculations')
    op.drop_table('pricing_calculations')
    op.drop_index(op.f('ix_peak_hours_city_code'), table_name='peak_hours')
    op.drop_table('peak_hours')
    # ### end Alembic commands ###
