"""empty message

Revision ID: 8aa575d8f287
Revises: 
Create Date: 2026-01-22 17:38:56.934852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8aa575d8f287'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emergency_contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergency_contacts_user_id'), 'emergency_contacts', ['user_id'], unique=False)
    op.create_table('emergency_numbers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('country_code', sa.String(length=10), nullable=True),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sos_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('emergency_number', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('triggered', 'active', 'resolved', 'cancelled', name='sosstatus'), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sos_requests_user_id'), 'sos_requests', ['user_id'], unique=False)
    op.create_table('sos_contact_notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sos_request_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('notification_sent', sa.Boolean(), nullable=False),
    sa.Column('notification_id', sa.UUID(), nullable=True),
    sa.Column('notified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['emergency_contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sos_request_id'], ['sos_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sos_contact_notifications_contact_id'), 'sos_contact_notifications', ['contact_id'], unique=False)
    op.create_index(op.f('ix_sos_contact_notifications_sos_request_id'), 'sos_contact_notifications', ['sos_request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sos_contact_notifications_sos_request_id'), table_name='sos_contact_notifications')
    op.drop_index(op.f('ix_sos_contact_notifications_contact_id'), table_name='sos_contact_notifications')
    op.drop_table('sos_contact_notifications')
    op.drop_index(op.f('ix_sos_requests_user_id'), table_name='sos_requests')
    op.drop_table('sos_requests')
    op.drop_table('emergency_numbers')
    op.drop_index(op.f('ix_emergency_contacts_user_id'), table_name='emergency_contacts')
    op.drop_table('emergency_contacts')
    # ### end Alembic commands ###
