"""initial database

Revision ID: 1d3fb2863dbc
Revises: 
Create Date: 2026-01-20 17:36:38.982738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d3fb2863dbc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('license_number', sa.String(length=100), nullable=True),
    sa.Column('license_expiry_date', sa.DateTime(), nullable=True),
    sa.Column('license_state_province', sa.String(length=100), nullable=True),
    sa.Column('vehicle_type', sa.Enum('bike', 'car', 'auto', 'premium_car', name='vehicletype'), nullable=True),
    sa.Column('vehicle_make', sa.String(length=100), nullable=True),
    sa.Column('vehicle_model', sa.String(length=100), nullable=True),
    sa.Column('vehicle_year', sa.Integer(), nullable=True),
    sa.Column('vehicle_color', sa.String(length=50), nullable=True),
    sa.Column('vehicle_plate_number', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'suspended', 'pending_verification', name='driverstatus'), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drivers_company_id'), 'drivers', ['company_id'], unique=False)
    op.create_index(op.f('ix_drivers_user_id'), 'drivers', ['user_id'], unique=False)
    op.create_table('driver_ratings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('passenger_id', sa.UUID(), nullable=False),
    sa.Column('ride_id', sa.UUID(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('punctuality_rating', sa.Float(), nullable=True),
    sa.Column('driving_rating', sa.Float(), nullable=True),
    sa.Column('vehicle_condition_rating', sa.Float(), nullable=True),
    sa.Column('communication_rating', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_ratings_driver_id'), 'driver_ratings', ['driver_id'], unique=False)
    op.create_index(op.f('ix_driver_ratings_passenger_id'), 'driver_ratings', ['passenger_id'], unique=False)
    op.create_index(op.f('ix_driver_ratings_ride_id'), 'driver_ratings', ['ride_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_driver_ratings_ride_id'), table_name='driver_ratings')
    op.drop_index(op.f('ix_driver_ratings_passenger_id'), table_name='driver_ratings')
    op.drop_index(op.f('ix_driver_ratings_driver_id'), table_name='driver_ratings')
    op.drop_table('driver_ratings')
    op.drop_index(op.f('ix_drivers_user_id'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_company_id'), table_name='drivers')
    op.drop_table('drivers')
    # ### end Alembic commands ###
