"""create cab_companies table

Revision ID: 5a295a294883
Revises: 
Create Date: 2025-12-22 16:04:40.148125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a295a294883'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cab_companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('company_type', sa.Enum('sole_proprietor', 'partnership', 'llc', 'corporation', name='companytype'), nullable=False),
    sa.Column('status', sa.Enum('active', 'suspended', 'pending_verification', 'closed', name='companystatus'), nullable=True),
    sa.Column('operating_region', sa.Enum('usa', 'canada', 'international', name='operatingregion'), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('state_province', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('address_line1', sa.String(length=255), nullable=False),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('business_email', sa.String(length=255), nullable=False),
    sa.Column('business_phone', sa.String(length=30), nullable=False),
    sa.Column('support_phone', sa.String(length=30), nullable=True),
    sa.Column('support_email', sa.String(length=255), nullable=True),
    sa.Column('website_url', sa.String(length=255), nullable=True),
    sa.Column('us_dot_number', sa.String(length=50), nullable=True),
    sa.Column('mc_number', sa.String(length=50), nullable=True),
    sa.Column('cvor_number', sa.String(length=50), nullable=True),
    sa.Column('business_license_number', sa.String(length=100), nullable=True),
    sa.Column('license_expiry_date', sa.DateTime(), nullable=True),
    sa.Column('insurance_policy_number', sa.String(length=100), nullable=True),
    sa.Column('insurance_expiry_date', sa.DateTime(), nullable=True),
    sa.Column('insurance_provider', sa.String(length=255), nullable=True),
    sa.Column('tax_id', sa.String(length=100), nullable=True),
    sa.Column('tax_percentage', sa.String(length=10), nullable=True),
    sa.Column('payout_bank_details', sa.JSON(), nullable=True),
    sa.Column('fleet_size', sa.String(length=20), nullable=True),
    sa.Column('service_areas', sa.JSON(), nullable=True),
    sa.Column('operating_hours', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cab_companies_owner_user_id'), 'cab_companies', ['owner_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cab_companies_owner_user_id'), table_name='cab_companies')
    op.drop_table('cab_companies')
    # ### end Alembic commands ###
