"""notification migration

Revision ID: 7186fe4c9a3d
Revises: 
Create Date: 2026-01-29 17:52:05.846255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7186fe4c9a3d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('notification_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('channels', sa.String(), nullable=False),
    sa.Column('fcm_message_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_status', 'notification_logs', ['status'], unique=False)
    op.create_index('idx_type_created', 'notification_logs', ['notification_type', 'created_at'], unique=False)
    op.create_index('idx_user_created', 'notification_logs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_notification_logs_created_at'), 'notification_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_notification_logs_user_id'), 'notification_logs', ['user_id'], unique=False)
    op.create_table('user_devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_token', sa.String(), nullable=False),
    sa.Column('device_name', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_platform', 'user_devices', ['platform'], unique=False)
    op.create_index('idx_user_active', 'user_devices', ['user_id', 'is_active'], unique=False)
    op.create_index('idx_user_platform', 'user_devices', ['user_id', 'platform'], unique=False)
    op.create_index(op.f('ix_user_devices_device_token'), 'user_devices', ['device_token'], unique=True)
    op.create_index(op.f('ix_user_devices_is_active'), 'user_devices', ['is_active'], unique=False)
    op.create_index(op.f('ix_user_devices_user_id'), 'user_devices', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_devices_user_id'), table_name='user_devices')
    op.drop_index(op.f('ix_user_devices_is_active'), table_name='user_devices')
    op.drop_index(op.f('ix_user_devices_device_token'), table_name='user_devices')
    op.drop_index('idx_user_platform', table_name='user_devices')
    op.drop_index('idx_user_active', table_name='user_devices')
    op.drop_index('idx_platform', table_name='user_devices')
    op.drop_table('user_devices')
    op.drop_index(op.f('ix_notification_logs_user_id'), table_name='notification_logs')
    op.drop_index(op.f('ix_notification_logs_created_at'), table_name='notification_logs')
    op.drop_index('idx_user_created', table_name='notification_logs')
    op.drop_index('idx_type_created', table_name='notification_logs')
    op.drop_index('idx_status', table_name='notification_logs')
    op.drop_table('notification_logs')
    # ### end Alembic commands ###
